<error errorId="c3a86e9c-00a5-490a-ba97-40346296b483" host="VIVEK-7020" type="System.NullReferenceException" message="Object reference not set to an instance of an object." source="DEMO.Services" detail="System.NullReferenceException: Object reference not set to an instance of an object.&#xD;&#xA;   at DEMO.Services.ADRoleService.GetUserSearchResult(String principalName, SearchResult&amp; searchResult)&#xD;&#xA;   at DEMO.Services.ADRoleService.get(String UserName)&#xD;&#xA;   at DEMO.API.Helpers.CustomAuthorizeAttribute.IsAuthorized(HttpActionContext actionContext)&#xD;&#xA;   at System.Web.Http.AuthorizeAttribute.OnAuthorization(HttpActionContext actionContext)&#xD;&#xA;   at System.Web.Http.Filters.AuthorizationFilterAttribute.OnAuthorizationAsync(HttpActionContext actionContext, CancellationToken cancellationToken)&#xD;&#xA;--- End of stack trace from previous location where exception was thrown ---&#xD;&#xA;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xD;&#xA;   at System.Web.Http.Filters.AuthorizationFilterAttribute.&lt;ExecuteAuthorizationFilterAsyncCore&gt;d__2.MoveNext()&#xD;&#xA;--- End of stack trace from previous location where exception was thrown ---&#xD;&#xA;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xD;&#xA;   at System.Web.Http.Controllers.AuthenticationFilterResult.&lt;ExecuteAsync&gt;d__0.MoveNext()&#xD;&#xA;--- End of stack trace from previous location where exception was thrown ---&#xD;&#xA;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xD;&#xA;   at System.Web.Http.Controllers.ExceptionFilterResult.&lt;ExecuteAsync&gt;d__0.MoveNext()" time="2017-08-03T19:32:31.5881387Z" />